### ISSUE TITLE
Why not install as devDependency ?

### ISSUE THREAD

**Issue by Vadorequest** [cyrilwanner/next-compose-plugins#15]
I just wonder why this isn't installed as dev dependency since it's not required at runtime but only at build time. Could anyone shine some light on this?

**Comment by cyrilwanner** [comment]
It is actually also required at runtime.
You define the plugins and use this package in the `next.config.js`. This config file is used in all phases of next.js, during development, production build and production server (https://github.com/zeit/next.js/blob/canary/packages/next-server/lib/constants.js#L3). So when you start your production server, next.js still parses this config file to, for example, know from where assets should be served etc. (you can also verify this by adding a console log to your next.config.js)

I hope that this clarifies why it can't be installed as a dev dependency. Otherwise, just reopen this issue or create a new one :)
